using System.Text;
using CppAst;

namespace AngelBindgen;

public static class Generator
{
    public static void Generate(CppCompilation ast, GeneratorConfig generatorConfig)
    {
        var targetScope = ast;
        // var targetScope = ast.Namespaces.FirstOrDefault(n => n.Name == "");
        // if (targetScope == null)
        // {
        //     Console.WriteLine("Could not find the target namespace.");
        //     return;
        // }

        GeneratorContext ctx = new GeneratorContext { Config = generatorConfig };

        foreach (var type in generatorConfig.PredefinedCppTypes)
        {
            ctx.RegisteredScriptTypes[type] = new TypeRegisterInfo();
        }

        foreach (var class_ in targetScope.Classes)
        {
            string className = class_.Name;
            ctx.RegisteredScriptTypes[className] = new TypeRegisterInfo();
        }

        foreach (var class_ in targetScope.Classes)
        {
            generateClass(ctx, class_);
        }
    }

    private static void generateClass(GeneratorContext ctx, CppClass class_)
    {
        string className = class_.Name;
        string includePath = Utils.ExtractRelativePath(class_.SourceFile, "src");

        var outputFilename = className + ".generated.cpp";

        ctx.Logger.Begin(outputFilename);

        var sb = new StringBuilder();

        foreach (var field in class_.Fields)
        {
            var typeSignature = ScriptSignatureResolver.ResolveScriptTypeSignature(ctx, field.Type);
            if (typeSignature == "") continue;

            sb.AppendLine(
                $$"""
                  bind.property("{{ScriptSignatureResolver.ResolveScriptTypeSignature(ctx, field.Type)}} {{field.Name}}", &{{className}}::{{field.Name}});
                  """);
        }

        foreach (var method in class_.Functions)
        {
            if (method.IsStatic) continue;

            string functionSignature = ScriptSignatureResolver.ResolveScriptFunctionSignature(ctx, method);
            if (functionSignature == "") continue;

            string parameterTypes = method.Parameters.Select(p => p.Type.FullName).Join(", ");

            string const_ = method.IsConst ? ", const_" : "";

            sb.AppendLine(
                $$"""
                  bind.method(
                    "{{functionSignature}}",
                    overload_cast<{{parameterTypes}}>(&{{className}}::{{method.Name}}{{const_}}));
                  """);
        }

        string content =
            $$"""
              // This file is auto-generated by AngelBindgen

              #include "raylib.h"

              #include <asbind20/asbind.hpp>
              #include <asbind20/operators.hpp>

              #ifdef AS_USE_NAMESPACE
              using namespace AngelScript;
              #endif

              namespace {{ctx.Config.ProjectNamespace}}
              {
                  std::function<void()> BindScript_{{className}}(asIScriptEngine* engine)
                  {
                      using namespace asbind20;
                      auto bind = asbind20::value_class<{{className}}>(engine, "{{className}}", asOBJ_POD | asOBJ_APP_CLASS_ALLINTS);
                      bind.behaviours_by_traits();
                      
                      return [engine, bind]() mutable{
                          {{sb.ToString().Trim().Replace(Environment.NewLine, Environment.NewLine + "            ")}}
                      };
                  }
              }
              """;

        var outputFilepath = Utils.CombineAndGetFullPath(ctx.Config.OutputDir, outputFilename);

        File.WriteAllText(Utils.CombineAndGetFullPath(outputFilepath, ""), content);

        ctx.Logger.End();
    }
}