using System.Text;
using CppAst;

namespace AngelBindgen;

public static class Generator
{
    public static void Generate(CppCompilation ast, GeneratorConfig generatorConfig)
    {
        var targetScope = ast;
        // var targetScope = ast.Namespaces.FirstOrDefault(n => n.Name == "");
        // if (targetScope == null)
        // {
        //     Console.WriteLine("Could not find the target namespace.");
        //     return;
        // }

        GeneratorContext ctx = new GeneratorContext { Config = generatorConfig };

        foreach (var type in generatorConfig.PredefinedCppTypes)
        {
            ctx.RegisteredScriptTypes[type] = new TypeRegisterInfo();
        }

        foreach (var class_ in targetScope.Classes)
        {
            string className = class_.Name;
            ctx.RegisteredScriptTypes[className] = new TypeRegisterInfo();
        }

        foreach (var class_ in targetScope.Classes)
        {
            generateClass(ctx, class_);
        }

        generateBindingEntryPoint(ctx);
    }

    private static void generateClass(GeneratorContext ctx, CppClass class_)
    {
        string className = class_.Name;
        ctx.SectionLogger.Begin(className);

        // string includePath = Utils.ExtractRelativePath(class_.SourceFile, "src");

        var sb = new StringBuilder();

        foreach (var field in class_.Fields)
        {
            var typeSignature = ScriptSignatureResolver.ResolveScriptTypeSignature(ctx, field.Type);
            if (typeSignature == "") continue;

            sb.AppendLine(
                $$"""
                  bind.property("{{ScriptSignatureResolver.ResolveScriptTypeSignature(ctx, field.Type)}} {{field.Name}}", &{{className}}::{{field.Name}});
                  """);
        }

        foreach (var method in class_.Functions)
        {
            if (method.IsStatic) continue;

            string functionSignature = ScriptSignatureResolver.ResolveScriptFunctionSignature(ctx, method);
            if (functionSignature == "") continue;

            string parameterTypes = method.Parameters.Select(p => p.Type.FullName).Join(", ");

            string const_ = method.IsConst ? ", const_" : "";

            sb.AppendLine(
                $$"""
                  bind.method(
                    "{{functionSignature}}",
                    overload_cast<{{parameterTypes}}>(&{{className}}::{{method.Name}}{{const_}}));
                  """);
        }

        var bindingFunctionName = $"BindScript_{className}";

        var output = ctx.RegisteredScriptTypes[className].Output;

        output.Name = bindingFunctionName;

        output.Definition =
            $$"""
              std::function<void()> {{bindingFunctionName}}(asIScriptEngine* engine)
              {
                  using namespace asbind20;
                  auto bind = asbind20::value_class<{{className}}>(engine, "{{className}}", asOBJ_POD | asOBJ_APP_CLASS_ALLINTS); // TODO!
                  bind.behaviours_by_traits();
                  
                  return [engine, bind]() mutable {
                      {{sb.ToString().Trim().Replace(Environment.NewLine, Environment.NewLine + "        ")}}
                  };
              }
              """;

        ctx.SectionLogger.End();
    }

    private static void generateBindingEntryPoint(GeneratorContext ctx)
    {
        ctx.SectionLogger.Begin("<ScriptBinding>");

        string cppContent =
            $$"""
              // This file is auto-generated by AngelBindgen

              #include "raylib.h"

              #include <asbind20/asbind.hpp>
              #include <asbind20/operators.hpp>

              #ifdef AS_USE_NAMESPACE
              using namespace AngelScript;
              #endif

              namespace
              {
                  {{
                      ctx.RegisteredScriptTypes.Select(kv =>
                              kv.Value.Output.Definition.Replace(Environment.NewLine, Environment.NewLine + "    ")
                          )
                          .Join(Environment.NewLine + Environment.NewLine + "    ")
                  }}
              }

              namespace {{ctx.Config.ProjectNamespace}}
              {
                  std::function<void()> BindScriptByGenerator(asIScriptEngine* engine)
                  {
                      std::vector<std::function<void()>> binds{};
                  
                      {{
                          ctx.RegisteredScriptTypes.Select(kv =>
                              $"binds.push_back({kv.Value.Output.Name}(engine));"
                          ).Join(Environment.NewLine + "        ")
                      }}
                      
                      return [binds_ = std::move(binds)]() mutable {
                          for (auto& bind : binds_)
                          {
                              bind();
                          }
                      };
                  }
              }
              """;

        var outputCppFilename = "ScriptBinding.generated.cpp";
        var outputCppFilepath = Utils.CombineAndGetFullPath(ctx.Config.OutputDir, outputCppFilename);

        File.WriteAllText(Utils.CombineAndGetFullPath(outputCppFilepath, ""), cppContent);

        var headerContent =
            $$"""
              // This file is auto-generated by AngelBindgen

              #pragma once

              #include <functional>
              #include <asbind20/asbind.hpp>

              namespace {{ctx.Config.ProjectNamespace}}
              {
                  std::function<void()> BindScriptByGenerator(asIScriptEngine* engine);
              }
              """;

        var outputHeaderFilename = "ScriptBinding.generated.hpp";
        var outputHeaderFilepath = Utils.CombineAndGetFullPath(ctx.Config.OutputDir, outputHeaderFilename);

        File.WriteAllText(Utils.CombineAndGetFullPath(outputHeaderFilepath, ""), headerContent);

        ctx.SectionLogger.End();
    }
}